sudo: required

language: node_js

node_js:
  - "node"

before_install:
  - npm install -g yarn@latest

install:
  - yarn install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn lint
  - yarn test:dev
  - NODE_ENV=production yarn test:prod
  - yarn build:prod

