sudo: required

language: node_js

node_js:
  - "node"

before_install:
  - npm install -g yarn@latest

install:
  - yarn install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - ./node_modules/.bin/karma start --browsers Firefox --single-run
  - NODE_ENV=production ./node_modules/.bin/karma start --browsers Firefox --single-run
  - npm run build:prod

