sudo: required

node_js:
  - stable
  - 6


install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - ./node_modules/.bin/karma start --browsers Firefox --single-run

